version: '2'

services:
    consul:
        image: bhuisgen/alpine-consul
        ports:
            - "8500:8500"
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect=1 -client 0.0.0.0 -ui    # minimal server options

    rabbitmq:
        depends_on:
            - consul
        image: bhuisgen/alpine-rabbitmq
        build: .
        #volumes:
            #- /host/data:/var/lib/rabbitmq                                 # volume for data
        environment:
            - CONSUL_AGENT=consul                                           # consul agent hostname/IP
            #- CONSUL_PORT=8500                                             # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix                                 # consul key prefix path
            - CONSUL_SERVICENAME=rabbitmq                                   # consul service name
            - CONSUL_SERVICETAGS=dev                                        # consul service tag
            - CONSUL_SERVICEPORT=5672                                       # consul service port
            - CONSUL_CHECKTYPE=tcp                                          # consul health check type
            - RABBITMQ_ERLANGCOOKIE=NYRIWPJAVRANPDAJVPJS                    # erlang cookie
            - RABBITMQ_MQTT=1                                               # enable MQTT
            - RABBITMQ_STOMP=1                                              # enable STOMP
            - RABBITMQ_PLUGINS=rabbitmq_event_exchange,rabbitmq_management  # enable plugins
            - RABBITMQ_USERNAME=rabbitmq                                    # administrator user
            - RABBITMQ_PASSWORD=rabbitmq                                    # administrator password
            - RABBITMQ_SSL=0                                                # enable TLS
            #- RABBITMQ_SSLCACERTFILE=/etc/ssl/certs/ca.pem                 # TLS CA certificates
            #- RABBITMQ_SSLCERTFILE=/etc/ssl/certs/server.pem               # TLS server certificate
            #- RABBITMQ_SSLKEYFILE=/etc/ssl/private/server.key              # TLS server key
            #- RABBITMQ_SSLDEPTH=2                                          # TLS CA chain verification depth
            - RABBITMQ_SSLVERIFY=verify_peer                                # TLS verification
            - RABBITMQ_SSLFAILIFNOPEERCERT=false                            # TLS fail if client has no certificate
            - RABBITMQ_RAMLIMIT=0.4                                         # RAM limit
            - RABBITMQ_DISKLIMIT=1000000000                                 # disk limit
            #- RABBITMQ_CLUSTER=rabbit@abbitmq-master                       # cluster to join
            #- RABBITMQ_CLUSTERRAM=1                                        # cluster RAM node
            #- RABBITMQ_CLUSTERWAIT=15                                      # delay slave startup if master starts at the same time
            #- RABBITMQ_CONFIGSCRIPT=/root/rabbitmq/config.sh               # custom configuration script

    #
    # CLUSTER
    #

    # rabbitmq1:
    #     depends_on:
    #         - consul
    #     image: bhuisgen/alpine-rabbitmq
    #     hostname: rabbitmq1
    #     volumes:
    #         - /host/data1:/var/lib/rabbitmq
    #     environment:
    #         - CONSUL_AGENT=consul
    #         #- CONSUL_PORT=8500
    #         - CONSUL_SERVICENAME=rabbitmq
    #         - CONSUL_SERVICETAGS=dev
    #         - CONSUL_SERVICEPORT=5672
    #         - CONSUL_CHECKTYPE=tcp
    #         - CONSUL_KEYPREFIX=path/prefix
    #         - RABBITMQ_ERLANGCOOKIE=NYRIWPJAVRANPDAJVPJS       # cookie must be shared with other nodes
    #         - RABBITMQ_USERNAME=rabbitmq
    #         - RABBITMQ_PASSWORD=rabbitmq
    #         #- RABBITMQ_CLUSTER=rabbit@rabbitmq2               # uncomment to rejoin a existing cluster if this node has crashed
    #
    # rabbitmq2:
    #     depends_on:
    #         - consul
    #     image: bhuisgen/alpine-rabbitmq
    #     hostname: rabbitmq2
    #     volumes:
    #         - /host/data2:/var/lib/rabbitmq
    #     environment:
    #         - CONSUL_AGENT=consul
    #         #- CONSUL_PORT=8500
    #         - CONSUL_SERVICENAME=rabbitmq
    #         - CONSUL_SERVICETAGS=dev
    #         - CONSUL_SERVICEPORT=5672
    #         - CONSUL_CHECKTYPE=tcp
    #         - CONSUL_KEYPREFIX=path/prefix
    #         - RABBITMQ_ERLANGCOOKIE=NYRIWPJAVRANPDAJVPJS       # cookie must be shared with other nodes
    #         - RABBITMQ_USERNAME=rabbitmq
    #         - RABBITMQ_PASSWORD=rabbitmq
    #         - RABBITMQ_CLUSTER=rabbit@rabbitmq1                # join existing cluster
    #         - RABBITMQ_CLUSTERWAIT=15                          # need to wait some time if master node starts at the same time
