version: '2'

services:
    consul:
        image: bhuisgen/alpine-consul
        ports:
            - "8500:8500"
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect=1 -client 0.0.0.0 -ui    # minimal server options

    nginx:
        depends_on:
            - consul
        image: bhuisgen/alpine-nginx
        ports:
            - "80:80"
        environment:
            - CONSUL_AGENT=consul                  # consul agent hostname/IP
            #- CONSUL_PORT=8500                    # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix        # consul key prefix path
            - CONSUL_SERVICENAME=nginx             # consul service name
            - CONSUL_SERVICETAGS=dev               # consul service tag
            - CONSUL_SERVICEPORT=80                # consul service port
            - CONSUL_CHECKTYPE=tcp                 # consul health check type
            - NGINX_TEMPLATE=upstream              # configuration template
            - NGINX_TEMPLATE_SERVICENAME=myservice # service name to proxify
            - NGINX_TEMPLATE_SERVICETAG=dev        # service tag to proxify
